name: more_functions
description: A dart package which provides a lot of helpers functions for easy development.
version: 0.0.1
homepage: https://github.com/elbeicktalat/dart_more_functions

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
